[package]
name = "playcaster"
description = "🎥 Turn any playlist into a Podcast feed"
version = "0.0.1"
license = "MIT OR Apache-2.0"
authors = ["Jessica Stokes <hello@jessicastokes.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
env_logger = "0.9"
hhmmss = "0.1"
log = "0.4"
rss = { version = "2.0", features = ["validation"] }
serde = "1.0"
serde_json = "1.0"
structopt = "0.3"
youtube_dl = { version = "0.7", default_features = false, features = ["yt-dlp"] }
url = { version = "2.2", features = ["serde"] }
