[package]
name = "playcaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
env_logger = "0.9"
hhmmss = "0.1"
log = "0.4"
rss = { version = "2.0", features = ["validation"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3"
toml = "0.5"
youtube_dl = { version = "0.7", default_features = false, features = ["yt-dlp"] }
