[package]
name = "vodsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
env_logger = "0.9.0"
hhmmss = "0.1.0"
log = "0.4.14"
serde_json = "1.0.74"

[dependencies.rss]
version = "2.0"
features = ["validation"]

[dependencies.youtube_dl]
version = "0.7.0"
default_features = false
features = ["yt-dlp"]
